basePath: /
host: localhost:8000
info:
  contact: {}
  description: This is an API for restaurant review management
  termsOfService: http://swagger.io/terms/
  title: Reviews API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
